# Generated by Django 3.2.4 on 2021-06-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the diagnose based on provided symptoms', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('symptoms', models.TextField(help_text='Enter a brief description of the symptoms', max_length=1000)),
                ('diagnose', models.ManyToManyField(help_text='Select a diagnose', to='diagnostic.Diagnose')),
            ],
        ),
    ]
