# Generated by Django 3.2.4 on 2021-06-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='diagnose',
        ),
        migrations.AddField(
            model_name='record',
            name='diagnose',
            field=models.ForeignKey(help_text='Select a diagnose', null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.diagnose'),
        ),
    ]
