# Generated by Django 3.2.4 on 2021-06-26 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnostic', '0002_auto_20210626_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnose',
            options={'permissions': (('can_create_diagnoses', 'Create diagnose'), ('can_assign_diagnose', 'Assign diagnose'))},
        ),
        migrations.AddField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
