# Generated by Django 3.2.4 on 2021-06-28 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnostic', '0003_auto_20210626_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Doctors'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Patients'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
