# Generated by Django 3.2.4 on 2021-06-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0004_auto_20210628_0659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnose',
            options={'permissions': (('can_create_diagnoses', 'Create diagnose'),)},
        ),
    ]
